mi_portal_web/mi_portal_web/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    
]

mi_portal_web/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home',),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('portafolio/', views.portafolio, name='portafolio'),
    path('testimonial/', views.testimonail, name='testimonail_list'),
    path('testimonial/register',views.testimonio_registro, name = 'testmonial_register'),
    path('events/register/',views.event_register_view, name='event_register'),
    path('events/',views.event_list_view, name='event_list'),
    ]

mi_portal_web/myapp/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
 
class Event(models.Model):
    name = models.CharField(max_length=100)  
    description = models.TextField()  
    fecha =models.DateField()
    capacidad = models.IntegerField()
    
class Portafolio(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='images/')
    link = models.URLField(blank=True, null=True)
    
class Testimonio(models.Model):
       nombre=models.CharField(max_length=150)
       testimonio=models.TextField()
       puesto=models.CharField(max_length=100)
       empresa=models.CharField(max_length=50)
  
    
def __str__(self):
       return self.name 

mi_portal_web/myapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .form import ContactForm ,EventForm , TestimonioForm
from .models import Event,Testimonio

def home(request):
    #return HttpResponse("Bienvenido a tu pagina")
    return render(request,'myapp/home.html')

def about(request):
    # return HttpResponse("Acerca de esta pagina")
    return render(request,'myapp/about.html')

def contact(request):
    if request.method == 'POST':
     form = ContactForm(request.POST)
     if form.is_valid():
        form.save()
        return redirect('home')
    else:
        form = ContactForm()
    return render(request,'myapp/contact.html',{'form': form})

def testimonail(request):
    # testimonail_data = [
    #     {'nombre':" Roberto", 'puesto':" CEO of M6.33 Tecnology", 'testimonio':"Excelente Servicio"},
    #     {'nombre':" Roberto", 'puesto':" CEO of M6.33 Tecnology", 'testimonio':"Excelente Servicio"},
    # ]
    testimonail_data = Testimonio.objects.all
    return render(request,'myapp/testimonail.html', {'testimonails': testimonail_data})

def testimonio_registro(request):
    if request.method == 'POST':
        form = TestimonioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('testimonail_list')
    else: 
        form = TestimonioForm()
    return render(request, 'myapp/testimonio_registro.html',{'form':form})    

def portafolio(request):
    projects = [
        {'name':" Pagina de Restaurante", 'description': 'Proyecto para cadena de restuarantes mexicanos','image':'images/img1.jpg','url': 'https://antonias.us/'},
        {'name':" Pagina de Inmobiliarias", 'description': 'Proyecto para venta de casas','image':'images/img2.jpg','url': 'https://www.urbanhouse.com.mx/'},
        {'name':" Pagina de Escuela", 'description': 'Proyecto para escuela de Psicologia','image':'images/img3.jpg','url': 'https://www.impotlax.org/'},
    ]
    return render(request,'myapp/portafolio.html', {'projects': projects})

def event_register_view(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('event_list')
    else:
        form = EventForm()
    return render(request,'myapp/event_register.html',{'form': form}) 

def event_list_view(request):
     events = Event.objects.all()  #Select * from Events   
     return render(request, 'myapp/event_list.html',{'events':events})
 
 
 #Crear el modelo para  portafolio y testimonio , 
 # crear el formulario alta de testimonios y portafolio

mi_portal_web/myapp/templates/myapp/_form.html
{% csrf_token %}
{%for field in form%}
    <div class="form-group">
        <label for="{{field.id_for_label}}">{{field.label}}</label>
        {{field}}
        {% if field.errors %}
            <div class="alert alert-danger">
                {{ field.errors}}
            </div>
        {% endif%}    
 </div>
{%endfor %}

mi_portal_web/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title%} About {% endblock title %}
{% load static %}
{%block content%}
 main
        <h1> Bienvenidos a esta pagina de acerca de<h1>
            <p> Esta es la pagina acerca de </p>
            Agregar otra tres paginas portafolio, our teams, testimonails. y le va agregar tres elemente con estilo
            <h2>sss</h2>
            h3

    </body>
    <p>
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
          Toggle width collapse
        </button>
      </p>
      <div style="min-height: 120px;">
        <div class="collapse collapse-horizontal" id="collapseWidthExample">
          <div class="card card-body" style="width: 300px;">
            This is some placeholder content for a horizontal collapse. It's hidden by default and shown when triggered.
          </div>
        </div>
      </div>
{% endblock content %} 

mi_portal_web/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} | Mi portal Web {% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <!--Inicia Menu-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <img src="{% static 'images/logo.png'%}" alt="" />
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'home' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portafolio' %}">Portafolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'testimonail_list' %}">Testimonios</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'event_register' %}">Eventos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!--Fin Menu-->
    <!--Inicia Main Content-->
    <div class="container-md">
      {% block content %} 

      {% endblock content %}
    </div>
    <!--Fina Main Content-->
    <!--Inicia scripts Menu-->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <!--Fin scripts Menu-->
  </body>
</html>

mi_portal_web/myapp/templates/myapp/contact.html
{% extends 'myapp/base.html' %} {% block title%} Contact {% endblock title %} {%
load static %} 
{%block content%}
    <h1>Bienvenidos a esta pagina de Contacto</h1>
    <form method="post" action="{{ contact }}">
        {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Name</label>
        {{form.name}}
    </div>
    <div class="form-group">
        <label for="id_email">Email</label>
        {{form.email}}
    </div>
    <div class="form-group">
        <label for="id_message">Message</label>
        {{form.message}}
    </div>
    <button type="submit" class="btn btn-primary">Send</button>
    </form>

{% endblock content %}

mi_portal_web/myapp/templates/myapp/event_list.html
{% extends 'myapp/base.html' %}
{% block title%} Lista Eventos {% endblock title %}
{%block content%}
<h2>Lista de Eventos</h2>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Fecha</th>
            <th>Capacidad</th>
        </tr>
    </thead>
    <tbody>
        {%for event in events %}
        <tr>
            <td>{{event.id}}</td>
            <td>{{event.name}}</td>
            <td>{{event.description}}</td>
            <td>{{event.fecha}}</td>
            <td>{{event.capacidad}}</td>
        </tr>
    {%endfor%}
 </tbody>
</table>
{% endblock content %}

mi_portal_web/myapp/templates/myapp/event_register.html
{% extends 'myapp/base.html' %}
{% block title%} Registar Eventos {% endblock title %}
<h2>Registrar Evento</h2>
{%block content%}
<form method= "post">
    {%include 'myapp/_form.html' %}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock content %}

mi_portal_web/myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% block title%} Home {% endblock title %}
{% load static %}
{%block content%}

        <h1> Bienvenidos a esta pagina Mi porta Web</h1>
            <p> Esta es la pagina de Inicio </p>
            <div id="carouselExample" class="carousel slide">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{% static 'images/img1.jpg'%}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'images/img2.jpg'%}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'images/img3.jpg'%}" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div> 
{% endblock content %} 

mi_portal_web/myapp/templates/myapp/portafolio.html
{% extends 'myapp/base.html' %}
{% block title%} Portafolio {% endblock title %}
{% load static %}
{%block content%}
<h1>Portafolio</h1>
<div class="row">
    {%for  project in projects %}
    <div class="card" style="width: 18rem;">
        <img src={% static project.image %} class="card-img-top" alt="...">
   <div class="card-body">
          <h5 class="card-title">{{project.name  }}</h5>
          <p class="card-text">{{ project.description }}</p>
          <a href={{ project.url }}  target="_blank" class="btn btn-primary">Visitar el sitio</a>
        </div>
      </div>


    {%endfor %}
</div>
     
{% endblock content %} 

mi_portal_web/myapp/templates/myapp/portfolio_register.html
{% extends 'myapp/base.html' %}

{% block title %}Register Portfolio{% endblock %}

{% block content %}
<h2>Register Portfolio</h2>
<form method="post" enctype="multipart/form-data">
    {% include 'myapp/_form.html' %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

mi_portal_web/myapp/templates/myapp/testimonail.html
{% extends 'myapp/base.html' %} {% block title%} Testimonail {% endblock title%} 
{% load static %} {%block content%}
<h1>Testimonios</h1>
<a href="{% url 'testmonial_register' %}">Agrega un testimonio</a>
<div class="row">
{%if testimonails%}
   {%for testimonio in testimonails%}
  <div class="card" style="width: 18rem">
    <h5 class="card-title">{{testimonio.nombre }}</h5>
    <div class="card-body">
   
    <p class="card-text"><b>Cargo:</b>{{ testimonio.puesto }}<i>Empresa:</i><span>{{ testimonio.empresa }}</span></p>
      <p class="card-text">{{ testimonio.testimonio }}</p>
    </div>
  </div>
  {%endfor %}
  {% else %}
  <p>No hay testimonio al momento</p>
{%endif%}
</div>

{% endblock content %}

mi_portal_web/myapp/templates/myapp/testimonio_registro.html
{% extends 'myapp/base.html' %}
{% block title%} Registar Testimonios {% endblock title %}
<h2>Registrar Testimonios</h2>
{%block content%}
<form method= "post">
    {%include 'myapp/_form.html' %}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock content %}